# Generated by Django 4.1.4 on 2022-12-15 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Vehicle', 'Vehicle'), ('Vessel', 'Vessel'), ('Motorcycle', 'Motorcycle')], default='Running', max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='vphotos/')),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=100)),
                ('inventorynumber', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('enginetype', models.CharField(max_length=100)),
                ('enginenumber', models.CharField(max_length=100)),
                ('enginecc', models.CharField(max_length=100)),
                ('capacity', models.CharField(max_length=100)),
                ('dateofimport', models.DateField(null=True)),
                ('fuelcapacity', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('tonage', models.IntegerField(null=True)),
                ('lastlocation', models.CharField(blank=True, max_length=100, null=True)),
                ('laststatus', models.CharField(blank=True, max_length=100)),
                ('servicedate', models.DateField(null=True)),
                ('issuedtounit', models.CharField(blank=True, max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsms.brand')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.CharField(choices=[('Running', 'Running'), ('Grounded', 'Grounded')], default='Running', max_length=100)),
                ('type', models.CharField(choices=[('Allotment', 'Allotment'), ('Maintenance', 'Maintenance')], default='Running', max_length=100)),
                ('remarks', models.TextField(max_length=255, null=True)),
                ('createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('statusapproved', models.BooleanField(default=False)),
                ('allotmentlocation', models.CharField(max_length=100, null=True)),
                ('allotmentunit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='vsms.unit')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='vsms.vehicle')),
            ],
        ),
    ]
